# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'NOVADRIVE'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_transformations'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  NOVADRIVE: # Substituído para o nome correto do projeto
    
    # 1. Configuração para a pasta onde ficam suas Dimensões
    # Substitua "dims" pelo nome exato da pasta que você usa dentro de "models/"
    dims:
      +schema: analysis
      +materialized: table # Opcional: já cria todas as dims como tabelas

    # 2. Configuração para a pasta onde ficam suas Análises
    # Substitua "analises" pelo nome exato da pasta
    analises:
      +schema: analysis
      +materialized: view  # Opcional: cria as análises como views

    # (Opcional) Se você tiver uma pasta staging, ela continuará indo para o schema padrão
    staging:
      +materialized: view